name: my_outdoor_footprint
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.8.4
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  connectivity_plus: ^4.0.1
  fl_country_code_picker: 0.1.4
  image_picker: 1.0.0
  fl_chart: 0.63.0
  url_launcher: 6.1.11
  flutter: 
    sdk: flutter
  url_launcher: ^6.1.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

