// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_manager.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseManager {
  FirebaseManager._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9mr1kpEztyS9uTrwLvy0wWEbVISktRKM',
    appId: '1:897647395536:android:a425b6976c40e0d43c14d5',
    messagingSenderId: '897647395536',
    projectId: 'my-outdoor-footprint',
    storageBucket: 'my-outdoor-footprint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eJvj-UD-PyArkNqMJ4LJAiZFDzpqYuA',
    appId: '1:897647395536:ios:0fa2719dc848e24f3c14d5',
    messagingSenderId: '897647395536',
    projectId: 'my-outdoor-footprint',
    storageBucket: 'my-outdoor-footprint.appspot.com',
    iosClientId:
        '897647395536-m1o1o56r5e2tvnat0vr3md24cq1i7hho.apps.googleusercontent.com',
    iosBundleId: 'com.outdoorfootprint.myoutdoorfootprint.myOutdoorFootprint',
  );
}
